### ISSUE TITLE
Remove trailing / leading white space on admin name values 

### ISSUE THREAD

**Issue by clhenrick** [CartoDB/data-services#212]
Thought I'd make a quick note of this here: 

Just attempted an import of this dataset and `Mexico ` was the only name that didn't geocode as it had a trailing white space. Seems like it should be an easy fix to remove trailing (as well as leading) white space before string matching with the geocoded data? 

```
name,region
Canada,North America
Mexico ,North America
United States,North America
Greenland,North America
```

**Comment by rafatower** [comment]
Issue moved to [CartoDB/cartodb #7988](https://github.com/CartoDB/cartodb/issues/7988) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rafatower** [comment]
Hi @clhenrick,

Sorry for getting back to you that late. The issue is solved now, though in a different repository (actually the geocoder was working OK, but the editor part was not merging back the results in the final table properly).

Please don't hesitate to send more bug reports. Eventually we take care of them one way or another :smiley: 

Cheers!

**Comment by clhenrick** [comment]
👍
