### ISSUE TITLE
Level 1 geocoding for Ukraine

### ISSUE THREAD

**Issue by jsanz** [CartoDB/data-services#228]
We have a user trying to geocode level 1 administrative regions for Ukraine and is having issues. I've made several tests without a lot of success.

On [this map (carto file)](https://github.com/CartoDB/data-services/files/711340/ukraine_adm1.map.on.2017-01-17.at.14.23.40.carto.zip) I've been able to geocode only some provinces using the column `Administrative center` from [this Wikipedia page](https://en.wikipedia.org/wiki/Administrative_divisions_of_Ukraine#Table).

You can also try geocoding manually for example `Odessa` region and it works, but not `Lutsk`:

```sql
select cdb_geocode_admin1_polygon('Odessa', 'Ukraine')
```

Finally, I've taken a look at the `geocoding` user tables but synonyms for `adm1` table are in Cyrillic so I think I'm not checking the correct tables regarding the geocoder.

```sql
select g.cartodb_id,
       g.description,
       g.name,
       s.name as s_name
  from adm1 g 
  join admin1_synonyms s 
    on g.global_id = s.global_id 
 where s.adm0_a3 like 'UKR'
```

How can I check the admin1 names for Ukraine?

**Comment by rafatower** [comment]
Hi

Sorry about the late response.

The data and the extension are strictly separated.

In order to setup the internal geocoder you can install the extension following these instructions:
https://github.com/CartoDB/data-services/tree/master/geocoder/extension

Then you can download and install the data it operates on using these scripts:
https://github.com/CartoDB/data-services/blob/master/geocoder/geocoder_download_dumps
https://github.com/CartoDB/data-services/blob/master/geocoder/geocoder_restore_dump
https://github.com/CartoDB/data-services/blob/master/geocoder/geocoder_download_patches.sh
https://github.com/CartoDB/data-services/blob/master/geocoder/geocoder_apply_patches.sh

To regenerate the admin1 tables, you should refer to this documentation:
https://github.com/CartoDB/data-services/tree/c4c261c89df55e132fa77c3018d0ad9f75c1dd19/geocoder/admin1#data-sources

and check the scripts under this directory:
https://github.com/CartoDB/data-services/tree/master/geocoder/admin1

Unfortunately there's no build script for the whole thing. There were some plans for it (using an Observatory-like ETL) but not prioritized yet. In practice no changes have happened in this geocoder for a very long while.

I'm closing this ticket. Feel free to reopen if you need further info (or just grab me for 5 min as we may solve whatever doubts on the spot quicker that way).

**Comment by jsanz** [comment]
Hi Rafa thanks for the detailed explanation, this user never come back but
I guess at some point we will need to revisit this and maybe think about
feeding the geocoder with DO datasets where the update process looks easier.
