### ISSUE TITLE
Update IP address database for geocoding

### ISSUE THREAD

**Issue by javitonino** [CartoDB/data-services#231]
From https://github.com/CartoDB/bigmetadata/issues/359

As far as I can see (i.e., onprem), it looks our IP address database dates back to 2014. As per our current contract and licensing model, we should be able to update and get the newest one.

We don't have any specific requests to do this, I just think 3 years is a lot of time ;-)

cc @danicarrion @hannahblue

**Comment by jaakla** [comment]
Currently (with 8-Mar-18 GeoLite2 ) source data has about 4M rows, our DB has 3M, so 25% is 'missing'. Considerations:
* It seems to be be quite easy to create new version to S3 and data-services database, old scripts are here: https://github.com/CartoDB/data-services/tree/master/geocoder/ip-addresses
* Some table structure changes may have happened, some minor (?) tweaks may be needed
* Maxmind is deprecating their open source table, they stop their updates by 1-Apr-2018, see [announcement](https://dev.maxmind.com/geoip/geoip2/geolite2/). 
* We should check their commercial offering (should have also better accuracy), and some competitors also (e.g. IP2Location™, https://www.digitalelement.com/ etc). 
* Current usage ([kibana](http://kibana4.cartodb.net/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:program,negate:!f,value:dataservices_api),query:(match:(program:(query:dataservices_api,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:function_name,negate:!f,value:cdb_geocode_ipaddress_point),query:(match:(function_name:(query:cdb_geocode_ipaddress_point,type:phrase))))),index:'logstash-*',interval:d,query:(query_string:(analyze_wildcard:!t,query:'*')),sort:!('@timestamp',desc)))): last 30 days ~126K geocodes, very uneven, many days 0, max day 40K

**Comment by juanignaciosl** [comment]
@jaakla `GeoLite2-City-Blocks-IPv4.csv` has 3060528 rows (~3M), not ~4M. I downloaded it [here ](https://dev.maxmind.com/geoip/geoip2/geolite2/) as explained in [the instructions](https://github.com/CartoDB/data-services/tree/master/geocoder/ip-addresses). Am I looking at the wrong file?

**Comment by jaakla** [comment]
It may be I summed ipv4 and ipv6 tables, don't recall the detail :(. Strangely the 1 month old version and latest one have quite different numbers for both csv files:
```
// older:
:GeoLite2-City-CSV_20180306 jaak$ wc -l GeoLite2-City-Blocks-IPv4.csv
 2662733 GeoLite2-City-Blocks-IPv4.csv
:GeoLite2-City-CSV_20180306 jaak$ wc -l GeoLite2-City-Blocks-IPv6.csv
 2039865 GeoLite2-City-Blocks-IPv6.csv
// updated:
:GeoLite2-City-CSV_20180403 jaak$ wc -l GeoLite2-City-Blocks-IPv4.csv
 3060529 GeoLite2-City-Blocks-IPv4.csv
:GeoLite2-City-CSV_20180403 jaak$ wc -l GeoLite2-City-Blocks-IPv6.csv
  275449 GeoLite2-City-Blocks-IPv6.csv
```

**Comment by juanignaciosl** [comment]
I've tested a couple of the missing ones against a couple of free IP geocoder webpages. They return something similar to the old values.

I think that returning "the most recent known location" is better than returning nothing, specially because that'd lead to regressions to some users (as some points would become null). I propose keeping the old values that are missing in the new table. Maybe a column with the year of the source can be added so we could eventually use it as a quality indicator. What do you think, @hannahblue ?

**Comment by juanignaciosl** [comment]
I've changed my mind after seeing more data and taking into account that we don't only geocode by exact coincidence but by nearest subnetwork:

We could just update them and see. Most of the missing results will be handled by getting the nearest subnetwork. Examples:

```sql
-- New values 2.216.185* subnetwork
# select network_start_ip, st_astext(the_geom) from ip_address_locations where network_start_ip::text like '::ffff:2.216.185%';
   network_start_ip   |       st_astext
----------------------+------------------------
 ::ffff:2.216.185.0   | POINT(-0.1122 53.4904)
 ::ffff:2.216.185.128 | POINT(-0.7408 53.5774)

-- Old values 2.216.185* subnetwork
# select network_start_ip, st_astext(the_geom) from ip_address_locations_backup where network_start_ip::text like '::ffff:2.216.185%';
   network_start_ip   |       st_astext
----------------------+------------------------
 ::ffff:2.216.185.0   | POINT(-1.35 53.4333)
 ::ffff:2.216.185.192 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.128 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.160 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.184 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.176 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.182 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.180 | POINT(-1.35 53.4333)
 ::ffff:2.216.185.181 | POINT(-0.8167 51.3667)
(9 rows)
```

For example, this is the result of geocoding the following IPs:

2.216.185.0 --> -1.35, 53.4333
2.216.185.1 --> -1.35, 53.4333
2.216.185.128 --> -1.35, 53.4333
2.216.185.180 --> -1.35, 53.4333
2.216.185.181 --> -0.8167, 51.3667
2.216.185.182 --> -1.35, 53.4333

**Comment by jaakla** [comment]
I think it is ok plan, advantage is to have also clear source database version. It is not accurate database in any case and if someone uses then for statistical purposes where approximation is accepted.

*For particular case I would consider -1.35 53.4333 more probable correct location than the others, just looking at map, but that's purely speculative.*

I try to figure why ipv6 table decreased from March to April almost 10x (from 2M to 270K rows), I imagine they may have done some subnet "compressions". 

p.s. this gave me idea to add one more metadata column to geocoded table: geocoding source data updated date, as with different base tables/services you may get different locations and this helps troubleshooting. For online geocoders this would be date of geocoding request. So whole geocoding metadata may have something like "provider: tomtom, datum: 05.10.2018, precision: rooftop". Just something to consider for https://github.com/CartoDB/cartodb/issues/12371

**Comment by jaakla** [comment]
The number of lost IP-s is similar to recent loss in specific city ipv6 location table, happened between March and April this year (less 1.7M: from ~2M to ~200K), so maybe this is the reason? Here is my copy of [last 3 month data files](https://drive.google.com/open?id=12G8L25WjKoZkFCasAS8W58c64xJFk1NN). In this sense it may be valuable to use March data instead of newer April or May. In the other hand we would have own interpretation of maxmind then; we don't know reason of this data removal - maybe it was complete garbage (but the map does not suggest this), illegal data or whatnot.

The visual comparison suggests that older (March) table did have many more locations, it was not just some technical compression of subnets:

<img width="837" alt="screenshot 2018-05-11 08 13 10" src="https://user-images.githubusercontent.com/5609650/39908046-ecb8b602-54f4-11e8-873e-4af0b5e00565.png">

<img width="1260" alt="screenshot 2018-05-11 08 18 53" src="https://user-images.githubusercontent.com/5609650/39908050-f1fb6ea2-54f4-11e8-99c5-78e34bce408b.png">

**Comment by juanignaciosl** [comment]
Thanks, @jaakla ! I'll use your copy of March data!

**Comment by juanignaciosl** [comment]
Repetition of [my previous "Some raw numbers" comment](https://github.com/CartoDB/data-services/issues/231#issuecomment-387813042). `ip_address_locations` is the new one with May ip4 and March ip6, and `ip_address_locations_backup` is the old one, so we can compare the effect of switching (see comments):

```sql
-- Total count of the new dataset
dataservices_db=# select count(1) from ip_address_locations;
  count
---------
 5113274
(1 row)

-- Previous dataset count
dataservices_db=# select count(1) from ip_address_locations_backup;
  count
---------
 2963525
(1 row)

-- Matching IPs. Using March is just an slightly improvement over May
dataservices_db=# select count(1) from (select network_start_ip from ip_address_locations intersect select network_start_ip from ip_address_locations_backup) x;
  count
---------
 1487905
(1 row)

-- A lot of new IPs
dataservices_db=# select count(1) from (select network_start_ip from ip_address_locations except select network_start_ip from ip_address_locations_backup) x;
  count
---------
 3625369
(1 row)

-- Again, a lot of loss
dataservices_db=# select count(1) from (select network_start_ip from ip_address_locations_backup except select network_start_ip from ip_address_locations) x;
  count
---------
 1475620
(1 row)
```

As your research showed, @jaakla , March dataset is likely to be better, but it doesn't fix the loss of IPs. Anyway, in order to do a proper comparation, 

I'll apply the update on Monday morning.

**Comment by juanignaciosl** [comment]
Production geocoders updated (CartoDB/data-services/pull/240).
