### ISSUE TITLE
South Sudan iso3 code is wrong

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/data-services#233]
We have `SDS` when is `SSD`

This comes from our table

```sql
          name           | rank |          created_at           |          updated_at           | the_geom | the_geom_webmercator | cartodb_id | adm0_a3 |        name_         
-------------------------+------+-------------------------------+-------------------------------+----------+----------------------+------------+---------+----------------------
 S. Sudan                |    0 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      41628 | SDS     | ssudan
 SSD                     |    0 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      41871 | SDS     | ssd
 SDS                     |    3 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      42074 | SDS     | sds
 SS                      |    4 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      42487 | SDS     | ss
 Republic of South Sudan |    5 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      42590 | SDS     | republicofsouthsudan
 S. Sud.                 |    8 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      43391 | SDS     | ssud
 South Sudan             |    9 | 2015-11-04 17:17:40.882056+00 | 2015-11-04 17:17:40.882056+00 |          |                      |      43658 | SDS     | southsudan
(7 rows)

```

And if you [check in wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) for the iso3166-1 you can see is `SSD`

**Comment by javitonino** [comment]
Seems like a job for the superheroes at RT cc @ramiroaznar

**Comment by ethervoid** [comment]
I've checked a bit. South Sudan is a relative new Country and its ISO code is not the same for every country so we should take the iso one which is `SSD`

You can check the different names importing and looking at the [natural earth dataset](http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-details/)

**Comment by AleGoiko** [comment]
I have commented where this stands on [this pr](https://github.com/CartoDB/data-services/pulls/236)

**Comment by amartinj** [comment]
We have two fixes for this issue: 

- [This PR](https://github.com/CartoDB/data-services/pull/236), where the table is 'fixed', but we are not suer if it's correct since there are many differences compared to the one we are currently using
- [This other PR](https://github.com/CartoDB/data-services/pull/237) where we simply fix the table and add iso codes for South Sudan

**Comment by ramiroaznar** [comment]
Let me know if you need acceptance! :-)

**Comment by amartinj** [comment]
done and deployed

**Comment by joehonton** [comment]
Version 5.1.1 ne_10m_admin_0_countries still has many columns with the incorrect "SDS", but also has many columns with the correct value "SSD".

(All of the ADM0_A3_* columns are still SDS.)

It's hard for me to know if this is by design or if it's a problem, since I don't know what those others columns mean.
